### ISSUE TITLE
OFDB ratings

### ISSUE THREAD

**Issue by rossinior** [sander1/OFDB.bundle#2]
Hi,

using Plex, I do not get my OFDB star ratings from many non-english movies though I configured the OFDB bundle to get the those ratings and though I have it at the top of the list of metadata agents.

My list of metadata agents is:
- OFDB
- TheMovieDB
- Freebase

Example:
The Invincables (1994) / Die Sieger (1994)

I get the movie description and FSK rating obviously from OFDB, but the "Bewertung" which is used for the star rating of Plex is left empty.

**Comment by sander1** [comment]
Just fixed this in the plexinc-agents fork of this agent: https://github.com/plexinc-agents/OFDB.bundle/commit/f26d490e62b96e939dc61827e1a21fe96aa8ce1d

**Comment by rossinior** [comment]
Thx. Workshop like a Charme now.
Am 01.02.2016 16:31 schrieb "Sander Spies" <notifications@github.com>:

**Comment by rossinior** [comment]
Hi Sander,

I am using your OFDB bundle for Plex quite a lot and I am writing you to
let you know that I just opened two new "issues" which really are
expansions of the current OFDB bundle...

Would be nice if you find the time to take over once again.

Thx mate.


2016-02-01 19:22 GMT+01:00 Oliver Rosenkranz <o.rosenkranz@gmail.com>:
