### ISSUE TITLE
Line 41, regexp not enough

### ISSUE THREAD

**Issue by rossinior** [sander1/OFDB.bundle#4]
metadata.title = metadata.title = re.sub(r"(.*), (Die|Der|Das|Ein|The)", r"\2 \1", title[0])

Should hold more Words...

As this movie shows...
http://www.ofdb.de/film/279794,Eine-Handvoll-Briefe

"Eine" should be added

As the search for "miserables" as movie title shows...
"Les" and "Los" (as well as "Le") should also be added.
And there are a lot of things that can be added to the title in [] brackets.

**Comment by sander1** [comment]
A couple more articles have been added: https://github.com/sander1/OFDB.bundle/compare/f26d490e62b96e939dc61827e1a21fe96aa8ce1d...bc35e800b21efbb2e287f98f2d6dc79cd2006b5e
